config/routes.rb
Rails.application.routes.draw do
  resources :boards

  root 'boards#new'

end

app/models/board.rb
require 'color-generator'

class Board < ActiveRecord::Base
  serialize :tile_colors, JSON

  DEFAULT_HEIGHT = 3
  DEFAULT_WIDTH = 4
  WHITE_AS_HEX = 'ffffff'

  after_initialize :create_defaults

  def create_defaults
    self.name ||= Faker::Lorem.word.capitalize
    self.height ||= DEFAULT_HEIGHT
    self.width ||= DEFAULT_WIDTH
    self.tile_colors ||= Array.new(width * height, WHITE_AS_HEX)
  end

  def update_colors_from_params(colors_param)
    required_colors = width * height
    if (colors_param.count < required_colors)
      colors_param.fill(WHITE_AS_HEX, -1, required_colors - colors_param.count + 1)
    end
    self.tile_colors = colors_param
    save
  end

  def color_at(row, column)
    if (columns.include?(column) && (rows.include?(row)))
      tile_colors[index_for(row, column)]
    else
      raise RangeError.new("Row #{row}, column #{column} is outside the #{width} x #{height} bounds of the grid")
    end
  end

  def columns
    0..(width - 1)
  end

  def rows
    0..(height - 1)
  end

  def index_for(row, column)
    row * width + column
  end

  def color_generator
    @color_generator = @color_generator || ColorGenerator.new(saturation: 0.5, value: 1.0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.update_colors_from_params(tile_colors_from_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to action: 'edit', id: @board.id }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params) && @board.update_colors_from_params(tile_colors_from_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.js { render @board.reload }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :width, :height, :created_at)
    end

    def tile_colors_from_params
      (params[:tile_colors] || '').split(',')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div class="board row"
  data-height="<%= board.height %>"
  data-width="<%= board.width %>"
>
  <div class="twelve columns">
  <% 0.upto(board.height - 1) do |row| %>
    <div class="board-row">
      <% 0.upto(board.width - 1) do |column| %>
        <% color = board.color_at(row, column) %>
        <div class="tile" style="background-color: #<%= color %>"
           data-row="<%= row %>" data-column="<%= column %>">
        </div>
      <% end %>
    </div>
  <% end %>
  </div>

  <div class="instructions twelve columns">Click on any square to change its color.</div>
</div>

app/views/boards/_board.js.erb
$('.board').replaceWith(
  '<%= escape_javascript(render partial: 'update', layout: false) %>'
);

app/views/boards/_form.html.erb
<%= form_for(@board, remote: ajax_submit) do |f| %>
  <div class="row">
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="row">
    <%= f.label 'Board name', class: 'two columns' %>
    <%= f.text_field :name, class: 'six columns' %>
  </div>

  <div class="row width-height-controls">
    <%= f.label :width, class: 'two columns' %>
    <%= f.number_field :width, class: 'two columns'  %>
    <%= f.label :height, class: 'two columns'  %>
    <%= f.number_field :height, class: 'two columns'  %>
  </div>

  <%= hidden_field_tag('tile_colors', @board.tile_colors.join(',')) %>

  <% if show_board %>
    <%= render partial: 'board', locals: { board: @board } %>
  <% end %>

  <div class="actions row">
    <%= f.submit class: 'four columns button-primary' %>

    <% if show_board %>
      <button type="button" class="reset four columns">White!</button>
      <button type="button" class="random four columns">Random!</button>
    <% end %>
  </div>
<% end %>

app/views/boards/_update.html.erb
<%= render partial: 'board.html', locals: { board: @board } %>

app/views/boards/edit.html.erb
<%= render partial: 'form',
     locals: {
       ajax_submit: true,
       show_board: true
     }
%>

<div id="notice-container" class="row">
  <!-- This container takes up space even when the notice is
  not visible, so that we don't move the page contents vertically
  when we show the notice -->

  <p id="notice"><%= notice %></p>
</div>

<div class="row">
  <%= link_to 'All Boards', boards_path %>
  <%= link_to 'New Board', new_board_path %>
</div>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<table class="index">
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= render partial: 'board.html', locals: { board: board } %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New board', new_board_path %>

app/views/boards/new.html.erb
<h1>New</h1>

<%= render partial: 'form', locals: { ajax_submit: false, show_board: false } %>

<%= link_to 'All Boards', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'board', locals: { ajax_submit: false, show_board: true } %>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'All Boards', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tiles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="application">
    <%= yield %>
  </div>
  <footer><a href="https://github.com/benshine/tiles" target="_blank">tiles by benshine</a></footer>
</div>

</body>
</html>